### ISSUE TITLE
Pylance does not recognize constructor params from attrs 

### ISSUE THREAD

**Issue by mmiicchh** [microsoft/pylance-release#226]
## Environment data

-   Language Server version: v2020.8.0
-   OS and version: macOs Mojave 10.14.6
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.8, pipenv 
-   VSCode version: 1.47.3

## Expected behaviour

Type checking should recognize attributes created by attrs library (PyCharm does).

## Actual behaviour

<img width="600" alt="Screen Shot 2020-08-10 at 2 12 47 PM" src="https://user-images.githubusercontent.com/64562879/89833127-5f6d0d80-db15-11ea-8a94-341de64dbdd9.png">

## Code Snippet / Additional information

```python

import attr
@attr.s
class Foo:
    bar: str = attr.ib()

Foo("aa")
```

**Comment by erictraut** [comment]
The attr library introduces some non-standard Python behaviors that can't be described by the Python type language. The case you mentioned above falls into this category.

If you're using attr mainly to describe data classes like in your example above, I recommend switching to the dataclass support that was introduced in Python 3.8. Pylance has full support for dataclass.

**Comment by mmiicchh** [comment]
Unfortunately we stuck with 3.6 at least for some time, so no dataclasses. Also, attrs does not seem to go anywhere: https://www.attrs.org/en/stable/why.html#data-classes, so it would be nice to see pylance (or vscode python in general) support it.

**Comment by jstriebel** [comment]
I second the request. dataclasses are great for many use-cases, but attrs has multiple features that are not available in dataclasses (e.g. regarding inheritance, default-argument order (e.g. using keyword-only constructers)). ` `mypy` has a plugin for `attrs`. I don't know anything about the details, but looking at #290 it seems like pyright/pylance might be able to use this.

PS @mmiicchh: If you want to use dataclasses, there's a backport for Python 3.6: https://pypi.org/project/dataclasses

**Comment by achimnol** [comment]
Another bump for supporting `attrs`.
The relationship of `attrs` and `dataclasses` is like that `simplejson` serves as a more feature-rich 3rd-party extension followed by the stdlib `json`.

**Comment by fried** [comment]
This has been really painful. Pretty much anytime I construct an attrs class I have to #type: ignore it

**Comment by silasary** [comment]
Several major libraries, including `aiohttp` use attrs, and pep-557 even suggests using attrs for more complicated use-cases (dataclasses as a module exists because attrs didn't want to be locked in the standard library's release cycle)

**Comment by willemkokke** [comment]
Just ran into this as well, which is scuppering my dream of a properly type checked 2.7/3.7+ compatible codebase. (2.7 can't be dropped due to having support older Maya versions).

**Comment by Tinche** [comment]
Since dataclasses and attrs are so similar (dataclasses basically being a strict subset), adding attrs support should be fairly straightforward in a technical sense, no? So I'm guessing the problem is a matter of process, since attrs is "just" a third-party library.

Also, dataclasses are not the way forward. It's basically for use in the standard library or if you don't have access to pip/third party packages. Most codebases would be better served by attrs, and that's not going to change.

**Comment by jrounds** [comment]
Adding my "please".  Also out of courtesy could you write the dev of attrs and let him know pylance has slotted is package for death =).  I mean is it possible to write plugins for pylance that will add attrs support? Autocomplete is basically the only reason I use an IDE it is a feature that cannot be "sort of there if I don't do X".

Every few months, I try to convert to vcode and every few months.  I think this is much better! and then something like this happens and I think "whelp back to pycharm".

**Comment by jakebailey** [comment]
Pylance/pyright don't have a plugin system and can't reuse plugins from mypy (as they are heavily tied with mypy's own analysis which works very, very differently to ours).

We've talked about plugins, but most typing community effort has been put into expanding typing itself to cover more ground without needing plugins (like new variadic generics, ParamSpec, better syntax, etc). I'd think we'd want to ensure that any plugin system we come up with is usable cross-type-checker (otherwise everyone will have to write their plugins over and over again).

Just to address:

> Since dataclasses and attrs are so similar (dataclasses basically being a strict subset), adding attrs support should be fairly straightforward in a technical sense, no? So I'm guessing the problem is a matter of process, since attrs is "just" a third-party library.

It's not trivial _because_ it's a third party library. Dataclasses are defined in PEPs, which have specific descriptions, release versions, etc, which make them possible to implement directly and know exactly when to apply custom behaviors. A third party library is not tied to any Python release schedule, is not beholden to formal definition of behaviors, etc. There's caveats that come with having an analysis effectively reimplement the runtime behavior of a third party library, where the library may change over time, users can run older versions of it, etc. This is a motivating factor for plugins shipped with libraries themselves (as they can describe themselves at a specific revision), but that's nontrivial too.

We haven't closed this issue. This is an enhancement that would of course provide benefit, it's just not as simple as just extending dataclass support and we need to devise a real plan to get there.

**Comment by craiglabenz** [comment]
Big plus one from me on the feature, and also a big plus one on @jakebailey's explanation that it would in no way be simple. Features that are simple to imagine are not necessarily simple to implement, and we should all respect the developer time it would take to do this correctly.

**Comment by erictraut** [comment]
Here's a partial solution that may help out some of you who don't have the choice of switching from `attrs` to `dataclass`. The idea is to use the stdlib `@dataclasses.dataclass` decorator for type checking purposes but `@attr.s` decorator at runtime. Since the two are so close in functionality, it may be sufficient for many use cases. Similar aliasing can be used for `dataclasses.field`.

```python
from typing import TYPE_CHECKING
import attr

if TYPE_CHECKING:
    import dataclasses
    attr_s = dataclasses.dataclass
    attr_f = dataclasses.field
else:
    attr_s = attr.s
    attr_f = attr.field

@attr_s(eq=True, order=True, frozen=True)
class MyClass:
    count: int = attr_f(default=3)
    name: str = attr_f(default="hi")
```

![Screen Shot 2021-03-27 at 6 14 34 PM](https://user-images.githubusercontent.com/7040122/112739322-5a37c400-8f28-11eb-9336-20ee0ba3e73a.png)

**Comment by hynek** [comment]
Hi, I’m the original author and maintainer of attrs. Since pylance’s support for attrs is existential for it in the long term, I’d be happy to cooperate with you however I can.

Steve Dower indicated that it would help if there’d be a fixed spec, but before I do anything I’d like to hear it from you directly, what _you_ would consider helpful.

Feel free to contact me privately.

P.S. I positively hate tooting my own horn, but attrs had 50,000,000 downloads in the past 30 days so I think it’s fair to say that support for it would be also beneficial for pylance/VS Code.

**Comment by erictraut** [comment]
@hynek, thanks for reaching out. Your timing is good. We've been discussing some ideas for how to support attrs and similar libraries that have "dataclass-like" semantics. I was planning to reach out to you to get your input on some of the ideas we were exploring and see if you have any alternative suggestions. I'll follow up with you privately within the next several days.

**Comment by erictraut** [comment]
We have been exploring ways to provide better support for `attrs` and other libraries that support semantics similar to `dataclass`. Pylance version 2021.4.2 (released earlier today) contains a proposed solution that is documented in [this spec](https://github.com/microsoft/pyright/blob/master/specs/dataclass_transforms.md#applying-to-attrs). If you want to try it, I've included instructions on how to modify your local copy of `attrs` (or `pydantic`) source code. We welcome early feedback.

I've started a [discussion in the pyright repo](https://github.com/microsoft/pyright/discussions/1782). Please post questions, comments, or feedback there.

**Comment by jakebailey** [comment]
With https://github.com/python-attrs/attrs/pull/796 merged, it seems very likely that `attrs` 21.1 will feature the dataclass transforms defined above, and therefore work in type checking, completion, hovers, and so on.

**Comment by hynek** [comment]
And attrs 21.1 has just shipped! Here's to hope for a bright shared future. :)

**Comment by craiglabenz** [comment]
Few threads have been more fun to watch than this one. Maximum hat tip to the humility and team spirit of every one who contributed to this coming together. The Python community will really benefit, and we all appreciate you!

❤️

**Comment by rt121212121** [comment]
I've updated to the latest attrs 21.2.0, and have pylance 2021.5.1.

Constructor attributes in a subclass now no longer flag as typing false positives.  However constructor attributes in a base class are not recognized. This is an improvement, but I thought I would just highlight that the problem is not fully solved in case no-one has pointed this out.

I've extracted one example from my project below. You can see that I still have to ignore the base class attributes in any constructor.

```
# The base class from the dependency.
@attr.s(slots=True, repr=False)
class TxInput:
    prev_hash = attr.ib()
    prev_idx = attr.ib()
    script_sig = attr.ib()
    sequence = attr.ib()

# The subclass from my project.
@attr.s(slots=True, repr=False)
class XTxInput(TxInput):
    value: Optional[int] = attr.ib(default=None)
    x_pubkeys: List[XPublicKey] = attr.ib(default=attr.Factory(list))
    threshold: int = attr.ib(default=0)
    signatures: List[bytes] = attr.ib(default=attr.Factory(list))
    script_type: ScriptType = attr.ib(default=ScriptType.NONE)

# Some code that instantiates the subclass.
        return XTxInput(
            prev_hash          = row.tx_hash, # type: ignore
            prev_idx           = row.txo_index, # type: ignore
            script_sig         = Script(), # type: ignore
            sequence           = 0xffffffff, # type: ignore
            threshold          = self.get_threshold(),
            script_type        = row.script_type,
            signatures         = [NO_SIGNATURE] * len(x_pubkeys),
            x_pubkeys          = x_pubkeys,
            value              = row.value,
            key_data           = KeyDataType(row.keyinstance_id, row.account_id, row.masterkey_id,
                                    row.derivation_type, row.derivation_data2)
        )
```

**Comment by erictraut** [comment]
You need to include type annotations for the base class fields, just like you did for the subclass. If you add those, it works.

**Comment by erictraut** [comment]
I think we can probably mark this issue as complete at this point.

**Comment by jakebailey** [comment]
Forgot about this; the transformers were added a while ago, and the behaviors that had been hardcoded errors had since been removed (#1627).

Further discussion about this is happening on https://github.com/microsoft/pyright/discussions/1782 or upstream in attrs.

**Comment by Crazy-Owl** [comment]
I'm still encountering this error now.

Minimal example to reproduce:

```python
import attr

@attr.s(slots=True)
class TestAttr:
    a = attr.ib(default=None)

k = TestAttr(1)
```

The error I see is `Expected no arguments to "TestAttr" constructor`

My Pylance is up-to-date: `v2022.5.3`, `attrs` package I use on my current project is version `19.2.0`.

How do I make Pylance work with this kind of setup?

**Comment by erictraut** [comment]
@Crazy-Owl, you would need to provide a type annotation for the field `a` if you want this to work. Type annotations are required for `dataclass` to treat the field as a data field, and `attrs.s` is modeled as a dataclass for type analysis purposes even though it has slightly different behaviors in some cases (such as this one, where no type annotation is provided).

```python
@attr.s(slots=True)
class TestAttr:
    a: int = attr.ib(default=None)
```

**Comment by Crazy-Owl** [comment]
> @Crazy-Owl, you would need to provide a type annotation for the field `a` if you want this to work. Type annotations are required for `dataclass` to treat the field as a data field, and `attrs.s` is modeled as a dataclass for type analysis purposes even though it has slightly different behaviors in some cases (such as this one, where no type annotation is provided).
> 
> ```python
> @attr.s(slots=True)
> class TestAttr:
>     a: int = attr.ib(default=None)
> ```

Thanks for the information! Is there a way of disabling only this specific message?

**Comment by erictraut** [comment]
The best way to make the error go away is to add the annotation. If you don't want to do that for some reason, you could add a `# type: ignore`, but that simply suppresses the error message rather than addressing the issue.

**Comment by gegnew** [comment]
Hi @erictraut are you sure this works? The code you posted, 
```python
import attr


@attr.s(slots=True)
class TestAttr:
    a: int = attr.ib(default=None)


k = TestAttr(1)
```

still gives me a `pyright` error `[Pyright reportGeneralTypeIssues] [E] Expected no arguments to "TestAttr" constructor`.

Relevant versions:
```
attrs==21.4.0
pyright==1.1.223
```

**Comment by erictraut** [comment]
I'm not able to repro the problem. I suspect it's because you are using such an outdated version of pyright. There have been 33 newer versions released since 1.1.223.

**Comment by msert29** [comment]
@erictraut - Is there any plans on supporting typing within the `attr.ib` in the near future?

```
import attr

@attr.s(slots=True)
class Example:
    a = attr.ib(type= int, default=None)
```

**Comment by debonte** [comment]
@msert29, since this issue is closed, please open a new issue with more details on what Pylance behavior you would like to see with `attr.ib`.
