### ISSUE TITLE
python.analysis.exclude does not work for ipynb

### ISSUE THREAD

**Issue by alanlivio** [microsoft/pylance-release#3644]
## Environment data
conda 22.9.0
Python 3.9.13
vscode extension Pylance v2022.11.32
pyright 1.1.280

## Repro Steps

1. install extension pylance 
2. edit user json to exclude ipynb files as follow
```json
"python.analysis.exclude": [
    "**/*.ipynb",
     ] 
``` 
3. open an ipynb file and common not imported function such as display()
5. You will receive the message "Expression value is unused"

**Comment by judej** [comment]
Triage notes: need to try with 8 after the extension as in `**/*.ipynb*`

**Comment by debonte** [comment]
This behavior was fixed for `ignore` and `strict` in https://github.com/microsoft/pylance-release/issues/2135

**Comment by alanlivio** [comment]
Many thanks for the comments @judej and @debonte. 
I tried "**/*.ipynb*" in both  VSCode "python.analysis.exclude" and ${workspaceFolder}/pyrightconfig.json but didn't work.

![image](https://user-images.githubusercontent.com/604808/202660058-0b763de4-c0e2-4243-82a7-6ab380bf5045.png)

The strange thing is that in #2135, cited by @debonte, the user @bschnurr said that it was fixed at 2022.8.51, but my version is  2022.11.32.

Any other suggestions?

**Comment by debonte** [comment]
> You will receive the message "Expression value is unused"

If this is a case where the last line of a cell is an expression and you are getting "Expression value is unused", try upgrading to 2022.11.31 to get the fix for https://github.com/microsoft/pylance-release/issues/3282.

> open an ipynb file and common not imported function...

Note that we can still show diagnostics for files in `exclude`. To prevent diagnostics from being shown for particular file(s), use the `ignore` setting instead. See https://github.com/microsoft/pyright/blob/main/docs/configuration.md#main-pyright-config-options.

**Comment by alanlivio** [comment]
Many thanks @debonte

I installed pylance 2022.11.31.
![image](https://user-images.githubusercontent.com/604808/202918283-484b7820-6483-478b-869a-2d7017e85d28.png)

I tried used both ``python.analysis.exclude` and `python.analysis.ignore` with `"**/*.ipynb*"` and have the same reportUndefinedVariable error.

![image](https://user-images.githubusercontent.com/604808/202918255-9dde8a40-92c1-456c-a9d9-759ce5df60d5.png)

**Comment by debonte** [comment]
@alanlivio, can you please provide the content of your "Python Language Server" log from VS Code's output pane?

**Comment by alanlivio** [comment]
Many thanks @debonte.
I double-checked the `"python.analysis.ignore": [ "**/*.ipynb*",... ` and it is working on both 2022.11.31. and 2022.11.32.
Sorry for the confusion. I think the issue can be closed.

**Comment by BlueskyFR** [comment]
Hey! How come an extra `*` is required at the end?

**Comment by rchiodo** [comment]
> Hey! How come an extra `*` is required at the end?

Because of the way notebooks are handled. The 'documents' in the notebook are not named `*.ipynb`. They instead have '*.ipynb' as part of their full path. They're usually something like `vscode-notebook-cell://<path to notebook.ipynb>.cell.py`.
