### ISSUE TITLE
Duplicated Suggestion in Jupyter Notebook

### ISSUE THREAD

**Issue by NelloHo** [microsoft/pylance-release#3674]
## Environment data

-   Language Server version: VS Code 1.73.1 (system stetup)
-   OS and version: Win 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10 

## Code Snippet

```python
any code
```

## Repro Steps

1. start a clean VS code without any settings and packages
2. install Microsoft's official Python package (which contains Pylance)
3. open Jupyter Notebook

## Expected behavior

show only one suggestion for each string

## Actual behavior

it will show duplicated suggestions 

![image](https://user-images.githubusercontent.com/99171663/203800675-98a253a8-b4ef-489d-af04-42c8b47c2d13.png)

## Logs

```
XXX
```

**Comment by NelloHo** [comment]
there's probably a hint for finding the bug :
1. open Jupyter Notebook 
2. disable Pylance 
3. restart VS code 
4. enable Pylance again.

the duplicated suggestions disappear

**Comment by JiaranYa** [comment]
almost the same bug:
python version :3.9.12

not only duplicated suggestions, but also duplicated labels and error reports

can also be solved by the above-mentioned hint

![20221125191427](https://user-images.githubusercontent.com/62545540/204038102-5c4ff258-6290-407a-a08a-e3e66c5068cb.png)

![image](https://user-images.githubusercontent.com/62545540/204038240-feb81572-f273-4010-90fe-8242de0e2821.png)

![image](https://user-images.githubusercontent.com/62545540/204038315-c65a8540-8467-42e2-a309-7fe72e679d88.png)

**Comment by shivamCode0** [comment]
This is also a similar issue. When I import another file in a Jupyter notebook, it sometimes shows this:

![image](https://user-images.githubusercontent.com/47765144/204096425-f574dd92-bd62-4d2c-b47a-b5a1bfbb6134.png)

It duplicates the same message for most things like this:
![image](https://user-images.githubusercontent.com/47765144/204096518-b7b6906a-cf49-4e90-a056-822bbc8569e6.png)

but one "copy" of the suggestions doesn't find certain variables

**Comment by jaymegordo** [comment]
https://github.com/microsoft/pylance-release/issues/3617 same issue? fixed by updating jupyter to pre-release... but also in general things seem super buggy rn

**Comment by judej** [comment]
Could you try using the new Jupyter notebook handler? The settings should have:

`"python.pylanceLspNotebooksEnabled": true`

**Comment by NelloHo** [comment]
> python.pylanceLspNotebooksEnabled

this is a unrecognizable command:
![image](https://user-images.githubusercontent.com/99171663/204605921-803ead12-dc66-4ca5-8e06-d33a44b36eed.png)

and even if I change and save the setting , it still shows duplicated suggestions:
![image](https://user-images.githubusercontent.com/99171663/204606107-87170bd9-4deb-4c7c-8897-5e9b905f14fc.png)

**Comment by bsaunders23** [comment]
This seems like a duplicate of https://github.com/microsoft/pylance-release/issues/3693, can someone merge the issues? Thanks!

**Comment by JiaranYa** [comment]
Thanks to @judej  and his issue #3617. I change Jypyter to pre-release version. now it works properly, even affecting .py files. You can try it

**Comment by bsaunders23** [comment]
Yep just saw that thanks @judej!

**Comment by judej** [comment]
This is fixed by a [duplicate](https://github.com/microsoft/vscode-jupyter/issues/12280) of this bug. Please reopen if you are still seeing this
