### ISSUE TITLE
pylance causing 100% CPU utilization frequently

### ISSUE THREAD

**Issue by AbdealiLoKo** [microsoft/pylance-release#4885]
Note - I know this is a generic issue which is there in the issue tracker. But I find this happens to me quite frequently. And I have checked a bunch of the previous issues were closed because logging information and troubleshoot information was not provided.
So, I created a new issue for my case ...

## Environment data
-   Language Server version: v2023.9.20
-   OS and version: Windows 10 with Ubuntu 22.04.3 on WSL2 
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.16 with miniconda

**VSCode version information**:
Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

## Code Snippet

I open vscode using `code .` in my WSL and when it starts it makes my laptop laggy and slow.
Even if I wait for 5-7 mins for it to do all its initialization stuff - the laptop is still slow and laggy (Moving the cursor is laggy).

Before vscode is on:
![novscode-wsl](https://github.com/microsoft/pylance-release/assets/2200743/b2370c90-ca4d-4b79-9d07-80f814a0f203)

After vscode has been on for 5mins (throughout this time it has 100% CPU util):
![after-vscode-running-for-5mins](https://github.com/microsoft/pylance-release/assets/2200743/a8c24ca0-62ac-4fbe-9b92-8f5a06967e63)
NOTE: The high CPU processes are all pylance processes when I go to the right in htop

## Logs
pylance logs: https://drive.google.com/file/d/1uocJdR2m2YfghvaLK6Ops35uSdX8Pvbj/view?usp=sharing

**Comment by debonte** [comment]
@AbdealiLoKo is your source code available in a public repository? Or could you provide it to us?

**Comment by AbdealiLoKo** [comment]
Hi @debonte the code is not public
And would be complicated for me to provide it to you

But I can run commands and try things as required

**Comment by JohnathanGander** [comment]
I'm having similar issues.  Creating a blank file causes an increase of 30% CPU usage.  It looks like it successfully looks up imports but color is never applied for different levels of the program.  Opening a Jupyter notebook causes an increase of 75% CPU usage.  Prior to this Pylance was working properly for .py files but would periodically stop working for .ipynb files.  When a notebook is open I get the notification in VSCode that Pylance is trying to parse my documents, which it never successfully does.  Disabling the Pylance extension returns CPU usage to normal levels.

Windows 10

VS Code information:
Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by debonte** [comment]
@JohnathanGander, please open a separate issue. With logs and ideally code that repros this. If they end up being the same issue we can close one of them later.

**Comment by debonte** [comment]
@AbdealiLoKo, the thing that stood out to me in your log was this. Analyzing `test_model_engine.py` is taking almost two minutes.

```text
2023-09-26 19:30:21.936 [info] [Info  - 7:30:21 PM] (14554) [BG(1)] Long operation: checking: /home/abdealiloko/corridor/corridor-platforms/apps/corridor-api/corridor_api_test/unit/engines/test_model_engine.py (104602ms)
```



Without access to your source code it will be impossible for us to reproduce and investigate this.

Can you try to bisect that file to determine which piece of code is resulting in the long analysis times and the provide us with a minimal repro?

**Comment by Tatsh** [comment]
I am getting this issue with my [macprefs](https://github.com/Tatsh/macprefs) project. I am on an M1 Max Mac. I disabled every extension except Pylance.

[trace.log](https://github.com/microsoft/pylance-release/files/12750785/trace.log)

From `ps`:

```
andrew.udvare.-nd 44224  99.8  0.3 1589261024 223328   ??  R    10:31am   5:39.47
/Applications/MacPorts/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node
/Users/andrew.udvare.-nd/.vscode/extensions/ms-python.vscode-pylance-2023.9.20/dist/server.bundle.js
--cancellationReceive=file:ce620fa2fd18ded3ebe129902ce7b233cbea68b9db --node-ipc --clientProcessId=44173
```

Python 3.11 provided by MacPorts

To reproduce:

1. Clone macprefs
2. Open the folder in VS Code
3. Open a Python file (like `macprefs/command.py`)
4. View htop or Activity Monitor, sorting by CPU %

![image](https://github.com/microsoft/pylance-release/assets/724848/7d7f460b-a6a2-4ceb-8c25-6ade7db5df09)

**Comment by Tatsh** [comment]
Downgrading Pylance to 2023.9.10 is a workaround.

**Comment by JohnYeung-dojjy** [comment]
I encountered similar issue, upgrading Pylance did not help much
The problem seems to be type check setting, I had type checking mode 'basic' on, turning it off solved the issue for me.

**Comment by JohnYeung-dojjy** [comment]
Update:
The cause might be me editing a ~6000 lines python file (it is a config file) on Azure cloud, maybe it is just the cpu being unable to support pylance's computation?

**Comment by AbdealiLoKo** [comment]
I am not able to reproduce this anymore - my WSL still hangs once in a week or so.
I'm reasonably sure it is with something in vscode - as I don't really have anything else open in the WSL.
But I cannot confirm if it is pylance cause it happens randomly and I don't have any monitoring that can help with that :(

**Comment by pdonorio** [comment]
Hey everyone, found my self with the 100% CPU of the "Code Helper (Plugin)" today.
Killing it / restarting didn't help, and closing VScode had it still running.

After many time investigating I've learned you can check in the PID process the command and it was pointing to Pylance... found this issue, but no real solutions, until [this SO](https://stackoverflow.com/a/62404722) lead me to think of looking into the logs (which after some more digging it's possible in `Python: Show Language Server Output` in VScode settings).

The logs showed that the server was chunking too many files and timing out.

Only by creating a `pyrightconfig.json` at the root of my repo and setting specific includes on where to look for, I was able to get the server / code helper back to normal.

See sample config in:
https://github.com/microsoft/pyright/blob/main/docs/configuration.md#sample-config-file
  
Hope this helps others.

**Comment by debonte** [comment]
I'm going to close this issue since @AbdealiLoKo is no longer able to repro it.

@b-per, since your issue seems to be symlink-related, please upgrade to yesterday's prerelease build (2023.12.104) and see if the issue is resolved. We made a big change to how we handle file URIs in that release.

If anyone else is still experiencing similar issues, please also upgrade to the latest prerelease -- if your issue still repros there, please open a new issue.

**Comment by b-per** [comment]
Thanks. I installed the pre-release and it is not fixed though:

```
2024-01-24 13:48:42.981 [info] [Info  - 13:48:42] (70266) Pylance language server 2023.12.104 (pyright version 1.1.347, commit 9ec6beba) starting
2024-01-24 13:48:42.982 [info] [Info  - 13:48:42] (70266) Server root directory: file:///path/.vscode/extensions/ms-python.vscode-pylance-2023.12.104/dist
2024-01-24 13:48:42.985 [info] [Info  - 13:48:42] (70266) Starting service instance "abcd"
2024-01-24 13:48:43.006 [info] [Info  - 13:48:43] (70266) Setting pythonPath for service "abcd": "/path/bin/python"
2024-01-24 13:48:43.007 [info] [Info  - 13:48:43] (70266) Setting environmentName for service "abcd": "3.9.17 (venvname)"
2024-01-24 13:48:43.007 [info] [Info  - 13:48:43] (70266) Loading configuration file at /path/pyrightconfig.json
2024-01-24 13:48:43.051 [info] [Info  - 13:48:43] (70266) Assuming Python version 3.9
2024-01-24 13:48:43.051 [info] [Info  - 13:48:43] (70266) No include entries specified; assuming /path
2024-01-24 13:48:53.102 [info] [Error - 13:48:53] (70266) Enumeration of workspace source files is taking longer than 10 seconds.
This may be because:
* You have opened your home directory or entire hard drive as a workspace
* Your workspace contains a very large number of directories and files
* Your workspace contains a symlink to a directory with many files
* Your workspace is remote, and file enumeration is slow
To reduce this time, open a workspace directory with fewer files or add a pyrightconfig.json configuration file with an "exclude" section to exclude subdirectories from your workspace. For more details, refer to https://github.com/microsoft/pyright/blob/main/docs/configuration.md.
```

I will open a new issue when I have time but will stick to v2023.11.10 for now

**Comment by debonte** [comment]
@b-per, when you open the issue, if you can provide access to a repo that reproduces the problem that would be appreciated. Without being able to repro this issue ourselves, it's unlikely that we'll make progress on this.

**Comment by pdonorio** [comment]
Another update:
* we can now set exclude / include in JSON config of VS code directly ([ref](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022911-7-september-2022-prerelease))
* having a monorepo I also had to use [higher index limit](https://github.com/microsoft/pylance-release/discussions/2608#discussioncomment-8174753)


(in particular I had to exclude the folders with symlinks, that looked like causing some infinite loops. I can't reproduce in a small repo, but it's happening in the big monorepo)

**Comment by Fleyderer** [comment]
My experience:

1) VS Code worked normally with every project, except current
2) It always worked fine until I wrote last 5-10 lines
3) After these lines I've got lagging IDE, 100% CPU usage by Pylance, written code is not highlighted, etc.
4) Uninstalling extensions, VSCode and my life didn't help at all

While localizing problem, I've found these rows and there was a problem assigning properties that were not implemented in the __init__ method of the class and were not annotated. When I initialized these properties with empty values and wrote annotations, everything was fixed.

**Comment by denivic** [comment]
This is still an issue - an annoying one at that.

I am experiencing very frequent spikes in CPU usage, which causes VSC to freeze for a couple of seconds. It happens so often that I'm sometimes forced to work on my desktop that has 32GB of RAM (and thus has no issues) rather than my laptop even though the laptop has a much better setup for this specific project.

Is there any news on when/if this will be fixed?

**Comment by dzid26** [comment]
Symlinked folders (WSL2) caused the issue for me.  https://github.com/commaai/openpilot  
Fixed with `python.analysis.exclude`
