### ISSUE TITLE
Pylance v2023.10.50 is incompatible with Python Extension v2020.8.109390

### ISSUE THREAD

**Issue by yakamoz423** [microsoft/pylance-release#5019]
## Environment data

-   Language Server version: v2023.10.50
-   OS and version: Windows 11 Pro 22H2 22621.2428
-   Python version (& distribution if applicable, e.g. Anaconda): 3.5.4

## Code Snippet

```python
XXX
```

## Repro Steps

Since I‘m using Python 3.5.4, I switched Python extension to v2020.8.109390 so that I can use the debugger. In previous versions everything works fine until v2023.10.50. I got `Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio ...`, but I actually did not do anything it listed above.

1. Switch Python extension to v2020.8.109390
2. Use latest Pylance
3. Open a Python file, you can see the Python extension shows 2 error messages
4. Switch Pylance to v2023.10.40, or use latest Python extension
5. It works

## Expected behavior

Python extension works fine

## Actual behavior

![image](https://github.com/microsoft/pylance-release/assets/45655135/c3f28000-4a57-429e-bd32-34c508e70daf)

## Logs

Output from Python Language Server:
```
[Info  - 11:20:59 AM] (5568) Pylance language server 2023.10.50 (pyright cfe56bfb) starting
[Info  - 11:20:59 AM] (5568) Server root directory: C:\Users\Yolo\.vscode\extensions\ms-python.vscode-pylance-2023.10.50\dist
[Error - 11:20:59 AM] Server initialization failed.
  Message: Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.
  Code: -32603 
[Error - 11:20:59 AM] Starting client failed
  Message: Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.
  Code: -32603 
```

**Comment by silent780** [comment]
Same issue,  Have to roll back to v2023.10.40

**Comment by msmhi52** [comment]
Just received the same message!

**Comment by cottrell** [comment]
Same. Broken.

**Comment by assombrance** [comment]
I have seemingly this problem too, on first glance, but I have a nuance to add: 
the versions are not the same, and rolling back didn't solve it.

So probably not the same problem in the end, but I'm posting it here anyway, in case it helps.

Some further investigation lead me to think that something is broken about the specific python version I use. Indeed, changing the python interpreter fixes the problem.

**Comment by emanuelegiorgi** [comment]
Same issue for me,
I have Python extension v2022.16.1 and Python 3.9.18.

It works if I roll back to v2023.10.40, as suggested here.

**Comment by cottrell** [comment]
Not eve 10.40 works. It's all broken.

**Comment by leontev-vyacheslav** [comment]
I am using Python v2022.8.0 extension and Python 3.16.15 in devcontainer. 
Today after updating Pylance I have the same big error. Pylance doesn't work at all.

**Comment by leontev-vyacheslav** [comment]
Absolutely perfectly it was helped to me downgrading to Pylance  2023.10.40 version. This is very good Pylance to me

**Comment by monopodog** [comment]
Rolling Pylance language server back to 2023.10.40 solved this for me. 99% of you probably know this already, but I had to muck around Google to figure out how to roll back to previous version, so if anyone needs it, here's the quick how to:

  - Open VS Code.
  - Click the Extensions icon in the left-hand pane (or Ctrl+Shift+X).
  - Scroll to the Pylance extension.
  - Click the tiny gear icon next to the Pylance extension.
  - Choose "Install another version …" from the context menu. 
  - Choose 2023.10.40 (or whatever version works for you).

**Comment by luabud** [comment]
Hey everyone. Unfortunately it's not feasible for us to maintain Pylance compatible with older versions of the Python extension. However, if the main reason why you're using an old version of the Python extension is support for debugging Python 2.7 or Python 3.5/3.6, there may be a better workaround so you can keep using the latest Pylance and Python extensions. 

We have a new [Python Debugger](https://marketplace.visualstudio.com/items?itemName=ms-python.debugpy) extension that we are shipping separately so people can keep using the latest versions of the Python extension while having support for debugging older versions of Python. Specifically, the Python Debugger extension versions  `2023.1.*` support debugging for Python versions 3.6 and older. 

This way you can continue updating the Pylance and Python extensions and only use this one older version of the Python Debugger extension.

**Comment by Tma2333-Scale** [comment]
I have similar problem with `v2023.18.0` of Python Extension as well. It does not happen right away. It just crashed randomly when I am using Jupyter notebook.

**Comment by allabur** [comment]
Same here with latest extension on Python (v2023.18.0) and Pylance (v2023.10.50). Changing to previous Pylance (v2023.10.40) worked for me aswell)

Error:
2023-10-27 20:03:33.046 [info] [Error - 8:03:33 PM] Restarting server failed
2023-10-27 20:03:33.046 [info]   Message: Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.
  Code: -32603

**Comment by OttomanZ** [comment]
> Hey everyone. Unfortunately it's not feasible for us to maintain Pylance compatible with older versions of the Python extension. However, if the main reason why you're using an old version of the Python extension is support for debugging Python 2.7 or Python 3.5/3.6, there may be a better workaround so you can keep using the latest Pylance and Python extensions.
> 
> We have a new [Python Debugger](https://marketplace.visualstudio.com/items?itemName=ms-python.debugpy) extension that we are shipping separately so people can keep using the latest versions of the Python extension while having support for debugging older versions of Python. Specifically, the Python Debugger extension versions `2023.1.*` support debugging for Python versions 3.6 and older.
> 
> This way you can continue updating the Pylance and Python extensions and only use this one older version of the Python Debugger extension.

I am working with Python 3.10 and it's still giving me the same error rolling back to a previous version fixed it.

**Comment by csf90-uk** [comment]
> Hey everyone. Unfortunately it's not feasible for us to maintain Pylance compatible with older versions of the Python extension. However, if the main reason why you're using an old version of the Python extension is support for debugging Python 2.7 or Python 3.5/3.6, there may be a better workaround so you can keep using the latest Pylance and Python extensions.
> 
> We have a new [Python Debugger](https://marketplace.visualstudio.com/items?itemName=ms-python.debugpy) extension that we are shipping separately so people can keep using the latest versions of the Python extension while having support for debugging older versions of Python. Specifically, the Python Debugger extension versions `2023.1.*` support debugging for Python versions 3.6 and older.
> 
> This way you can continue updating the Pylance and Python extensions and only use this one older version of the Python Debugger extension.

The issue is happening even when using the latest versions of both Pylance and Python extensions.

**Comment by rchiodo** [comment]
For everybody that's reproing the issue, can you state:

- VS Code Version?
- Local or remote?
- Python extension version?

Thanks. We can't seem to reproduce it in house. 

Note: This error is expected if you're not actually using VS code (like VS codium or Cursor). It is NOT expected if you're using VS code through SSH/WSL/Dev Container. Those should work.

**Comment by imkSushi** [comment]
This issue started today for me.
VS Code 1.83.1
Remote (WSL on same machine)
Python extension version v2023.18.0

**Comment by rchiodo** [comment]
Can you try [2023.10.53](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/vscode-pylance/2023.10.53/vspackage)? I wonder if it's related to this issue: https://github.com/microsoft/vscode/issues/196740. Our best guess on the other issue is that the crashes in the Pylance server are starving the VS code extension host, preventing other things from working. It might be preventing the new message we added that verifies we're running inside of VS code.

**Comment by rchiodo** [comment]
If you see this in the `Python Language Server` output: 

```python
Debug Failure. Unable to find notebook URI for vscode-notebook-cell:
```

2023.10.53 might be the fix for the problem. It fixed that error.

**Comment by rchiodo** [comment]
> > For everybody that's reproing the issue, can you state:
> > 
> > * VS Code Version?
> > * Local or remote?
> > * Python extension version?
> > 
> > Thanks. We can't seem to reproduce it in house.
> > Note: This error is expected if you're not actually using VS code (like VS codium or Cursor). It is NOT expected if you're using VS code through SSH/WSL/Dev Container. Those should work.
> 
> MacOS Sonoma 14.0 VS Code: 1.83.1 Pylance: v2023.10.50 Python: 3.11.5
> 
> Local workspace. Virtual Python environment. Using JupyterNotebooks. Rolling back to Pylance v2023.10.40 seems to have fixed the problem. Issue happened in general use, switching between notebooks, scrolling. I haven't been actively executing code all that often.

Sorry @csf90-uk what's your Python extension version? You listed your Python version, but the Python extension needs to be a certain version for Pylance to work too.

**Comment by cbenitez81** [comment]
Vs Code version: 1.83.1
Remote: SSH
python 3.11.3

**Comment by Tma2333-Scale** [comment]
> For everybody that's reproing the issue, can you state:
> 
> * VS Code Version?
> * Local or remote?
> * Python extension version?
> 
> Thanks. We can't seem to reproduce it in house.
> 
> Note: This error is expected if you're not actually using VS code (like VS codium or Cursor). It is NOT expected if you're using VS code through SSH/WSL/Dev Container. Those should work.

VS Code Version: 1.83.1 
Remote: SSH 
Python extension version: v2023.18.0

Since my problem mainly happened during use of notebook, Jupyter extension version: v2023.9.1102792234. This could purely depend on the workload at the time is mainly using notebook. The symptoms for me is basically, when typing/scrolling through the code, pylance died with the message, also brought down the Jupyter kernel as well, no way to restart the kernel. Needs to reload the window to restart.

**Comment by rchiodo** [comment]
> Vs Code version: 1.83.1 Remote: SSH python 3.11.3

Sorry the Python extension. It should be something like this:

![image](https://github.com/microsoft/pylance-release/assets/19672699/0dabd196-fafd-4ca9-bba9-550477967f6c)

**Comment by csf90-uk** [comment]
> > > For everybody that's reproing the issue, can you state:
> > > 
> > > * VS Code Version?
> > > * Local or remote?
> > > * Python extension version?
> > > 
> > > Thanks. We can't seem to reproduce it in house.
> > > Note: This error is expected if you're not actually using VS code (like VS codium or Cursor). It is NOT expected if you're using VS code through SSH/WSL/Dev Container. Those should work.
> > 
> > 
> > MacOS Sonoma 14.0 VS Code: 1.83.1 Pylance: v2023.10.50 Python: 3.11.5
> > Local workspace. Virtual Python environment. Using JupyterNotebooks. Rolling back to Pylance v2023.10.40 seems to have fixed the problem. Issue happened in general use, switching between notebooks, scrolling. I haven't been actively executing code all that often.
> 
> Sorry @csf90-uk what's your Python extension version? You listed your Python version, but the Python extension needs to be a certain version for Pylance to work too.

Apologies. v2023.18.0

**Comment by StellaHuang95** [comment]
@csf90-uk @Tma2333-Scale and for those who have python extension 2023.6.0 or a newer version installed, were you seeing the exact same message `You may install and use any number of copies of the software only with Microsoft Visual Studio...`, or did you experience a different Pylance crash?

**Comment by csf90-uk** [comment]
Yes, the same error.

**Comment by philipmassie** [comment]
> For everybody that's reproing the issue, can you state:
> 
> * VS Code Version?
> * Local or remote?
> * Python extension version?
> 
> Thanks. We can't seem to reproduce it in house.
> 
> Note: This error is expected if you're not actually using VS code (like VS codium or Cursor). It is NOT expected if you're using VS code through SSH/WSL/Dev Container. Those should work.

VS Code Version: 1.83.1
Remote: SSH
Python extension version: v2023.18.0

**Comment by gel-alex** [comment]
Same here, only downgrading pylance worked.

**Comment by heejaechang** [comment]
can we get some screenshots of extensions tab and output window when the issue is happening?

![image](https://github.com/microsoft/pylance-release/assets/1333179/b9db54ef-0bb3-4f08-844d-5e57f18f38c1)

![image](https://github.com/microsoft/pylance-release/assets/1333179/f54a73c2-cb37-4ded-b8f7-de4921b10293)

currently, we can't seem to repro and none of report here provide some actionable info for us to dig in.

those screenshots will at least let us know whether we are using right env to repro the issue.

**Comment by quillaja** [comment]
Most recent VSCode, pylance, etc. For me, it's breaking on the conda environment provided by ArcGIS Pro 3.1.3, which uses python v3.9.16. Worked "fine" (although pylance can't produce intellisense for all submodules of `arcpy` even on the best days) last time I used this env a few months ago. Going back a few versions of pylance fixed it for me.

**Comment by heejaechang** [comment]
@quillaja I am sorry to hear that the latest pylance didn't work as expected but we will need more info to find out why that happened. providing screenshots as above would help us to find out root issue!

thank you

**Comment by heejaechang** [comment]
can you show us not only `pylance` version but `python extension` version as well? as long as we know, the failure should only happen when `pylance extension` is used with very old `python extension` we no longer support. 

that said, your screen shows different issue than this issue - `Request initialize failed with message: You may install and use any number of copies of ...`

you probably want to open a new issue so we can take a look rather than mixing with this issue.

thank you.

**Comment by heejaechang** [comment]
@quillaja I think your particular issue should be fixed by the latest pylance prerelease (2023.10.53)

**Comment by liuxhit** [comment]
feedback my timeline:
* 2023.10.50 bad
* (found this issue, same `Code: -32603`)
* 2023.10.53 bad
* 2023.10.40 good

**Comment by neljo8m** [comment]
I'm having the same issue.
All version info is in the screenshot.
![Screenshot 2023-11-02 at 12 33 18](https://github.com/microsoft/pylance-release/assets/136503993/247b5a94-85b0-4c58-9e57-3479e793b477)

**Comment by heejaechang** [comment]
@neljo8m thank you very much for the screenshot. is your dev environment `vscode`, `local`, `mac` and this happen with any `python file`?

**Comment by heejaechang** [comment]
@liuxhit can you share the screenshot?

**Comment by neljo8m** [comment]
> @neljo8m thank you very much for the screenshot. is your dev environment `vscode`, `local`, `mac` and this happen with any `python file`?

Yes, I'm using `VS Code 1.83.1`, `local` on `Mac OS 13.6.1`.
It is not specific to any particular file.  And I have not noticed any pattern when it happens.
I did notice some folks here mentioned that it was related to Jupyter.
So it is interesting, this time, it did happen just after I ran a few lines of code in Jupyter, using Py comments.
Like this:
```python
# %%
# run some python code here
v = "test"
print( f"{v=}" )
# %%
```
When I pressed <Shift+Enter> to run that in Jupyter, it ran fine.
But shortly after that, I received the Pylance error.
So maybe it is related to Jupyter in some way.  Or maybe Jupyter just starts the problem.
I have the Jupyter plugin v2023.10.1003070148 (Microsoft)

**Comment by heejaechang** [comment]
@neljo8m there is a separate jupyter related issue that is fixed in pylance `2023.10.53`. without log, hard to know whether which issue you are hitting. this issue is specifically about `Initialization failure` issue due to using `the latest pylance` with `python extension` we no longer support.

**Comment by neljo8m** [comment]
> @neljo8m there is a separate jupyter related issue that is fixed in pylance `2023.10.53`. without log, hard to know whether which issue you are hitting. this issue is specifically about `Initialization failure` issue due to using `the latest pylance` with `python extension` or `jupyter extension` we no longer support.

You see the version of the Python extension I am using.  So it looks like that does not apply to me.

**Comment by heejaechang** [comment]
@neljo8m 
> You see the version of the Python extension I am using. So it looks like that does not apply to me.

are you referring jupyter issue or `intialization failed issue`?

**Comment by neljo8m** [comment]
Sorry, I was not clear.
I was referring to your comment about the "issue due to using the latest
pylance with python extension or jupyter extension we no longer support".
Since I am using the latest versions, that issue does not apply.

**Comment by neljo8m** [comment]
> @neljo8m
> 
> > You see the version of the Python extension I am using. So it looks like that does not apply to me.
> 
> are you referring jupyter issue or `intialization failed issue`?

Sorry, I was not clear.
I was referring to your comment about the "issue due to using the latest
pylance with python extension or jupyter extension we no longer support".
Since I am using the latest versions, that issue does not apply.

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2023.11.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231121-8-November-2023-PreRelease)

**Comment by bilzard** [comment]
@bschnurr Thank you for announcing.

> This issue has been fixed in prerelease version 2023.11.21, which we've just released.

You mean version 2023.11.12?

**Comment by debonte** [comment]
> You mean version 2023.11.12?

Yes, thanks. Fixed above.

**Comment by ljnsn** [comment]
This issue is still (again?) happening on version 2024.12.3 of the Python extension.

**Comment by debonte** [comment]
@ljnsn, questions for you:
1. Why are you using a 9-month old version of the Python extension? 
2. What version of Pylance are you trying to use?
3. Pylance is only supported in official builds of VS Code. Are you using one?

We don't maintain a mapping of compatible historical versions of the Pylance and Python extensions. My recommendation would be to update to the latest of both.

**Comment by ljnsn** [comment]
@debonte thanks for the quick response!

1. That's the version that got installed, isn't it the latest one? https://github.com/microsoft/vscode-python/releases/tag/v2024.12.3 released four days ago?
2. Pylance is 2024.8.1
3. It's the build provided by my package manager, so not the official one. vscode is version 1.91.1

> We don't maintain a mapping of compatible historical versions of the Pylance and Python extensions. My recommendation would be to update to the latest of both.

I understand, but the versions I'm using are the latest ones, aren't they?

**Comment by debonte** [comment]
Oh, I'm sorry. I forgot that the Python extension has a different versioning approach than us. I was interpreting xxxx.12.3 as a December release and didn't even look at the year.

> It's the build provided by my package manager, so not the official one. vscode is version 1.91.1

Is this VS Code OSS then? Pylance is only supported in the official builds. Try downloading and installing from the VS Code website and I think you'll find that it works.

**Comment by ljnsn** [comment]
Yes, it's a version of VS Code OSS. I previously never had any issues with Pylance/Python on this build, even though it's not officially supported. I'll wait for an update from the repo maintainer and see if it works with 1.92.x, otherwise I'll have to keep it updated myself.

**Comment by RitchieP** [comment]
I'm currently facing this error with Python `v2025.14.0` and Pylance `v2025.4.1`

Had to downgrade to `v2025.6.1` for it to work

**Comment by rchiodo** [comment]
> I'm currently facing this error with Python v2025.14.0 and Pylance v2025.4.1 
Had to downgrade to v2025.6.1 for it to work

This is on purpose. Newer Python extensions don't work with older Pylance.

**Comment by RitchieP** [comment]
@rchiodo but I don't see a newer version for Pylance.

**Comment by rchiodo** [comment]
You must not be using VS code then. The newest in VS code is version 2025.8.3 (as of this comment)

Pylance isn't supported anywhere else though.

**Comment by RitchieP** [comment]
That's weird. I'm using VS Code Insiders. Though not the common VS Code, I imagine that the Pylance extension is the same.

**Comment by rchiodo** [comment]
Yes, I'm using insiders as well. For me I'm using these versions:

Python extension:
Name: Python
Id: ms-python.python
Description: Python language support with extension access points for IntelliSense (Pylance), Debugging (Python Debugger), linting, formatting, refactoring, unit tests, and more.
Version: 2025.16.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python

Pylance extension:
Name: Pylance
Id: ms-python.vscode-pylance
Description: A performant, feature-rich language server for Python in VS Code
Version: 2025.8.100
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance

Both of which I installed through the extensions panel in VS code.

**Comment by RitchieP** [comment]
Hmph, that's pretty weird. It says I have the newest version (both release and pre-release).

<img width="795" height="193" alt="Image" src="https://github.com/user-attachments/assets/54e70bec-dc93-49d5-8821-3d8fba722f44" />

But it fails. When I try to press on `install a specific version`. It tells me I'm still on the old version.

<img width="799" height="218" alt="Image" src="https://github.com/user-attachments/assets/9b0e8b3d-4761-4684-8fc2-ccd9968a8c76" />

**Comment by RitchieP** [comment]
When I uninstall the extension, it shows me that I'm able to install the latest version. But upon installing, it actually installs the old `2025.4.1` version.

**Comment by RitchieP** [comment]
I resolved it by updating my VS Code. Guess it was a version incompatibility issue with VS Code. Appreciate the help!
