### ISSUE TITLE
Derived method completions use incorrect return type annotations when differing by `async` modifier.

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/pylance-release#5542]
Possibly related to #4831?

## Environment data

-   Language Server version: v2024.2.104
-   OS and version: Windows
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12

## Code Snippet

Minimal example:

```python
from typing import Awaitable

class Base:
    def yadda(self) -> Awaitable[int]:
        return 42
    
class Derived(Base):
    async def y$
```

## Repro Steps

Assume `$` is the cursor. Request completions at the cursor. Commit to the completion entry for `__aenter__`.

## Expected behavior

For minimal example:

```python
class Base:
    def yadda(self) -> Awaitable[int]:
        return 42
    
class Derived(Base):
    async def yadda(self) -> int:
        return super().yadda()
```

## Actual behavior

Pylance annotates uses the type that works for the non-`async` base, but one that does not work for the `async` derived type. The derived method is marked as `async`, so the method shouldn't declare it returns an `Awaitable`, a `Coroutine`, or whatever.

```python
class Base:
    def yadda(self) -> Awaitable[int]:
        return 42
    
class Derived(Base):
    async def yadda(self) -> Awaitable[int]:
        return super().yadda()
```

_______

Here's something closer to what I actually ran into:

```python
from typing import AsyncContextManager

class Yadda(AsyncContextManager):
    async def _$
```

**Expected**

```python
class Yadda(AsyncContextManager):
    async def __aenter__(self) -> Self:
        return await super().__aenter__()
```

**Actual**

```python
class Yadda(AsyncContextManager):
    async def __aenter__(self) -> Coroutine[Any, Any, _T_co]:
        return await super().__aenter__()
```

**Comment by DanielRosenwasser** [comment]
(generator functions might not have this issue since I don't think they become generators unless they have a yield statement)

**Comment by DanielRosenwasser** [comment]
also, it's not entirely about whether the modifiers differ - in the second example I gave, `__aenter__` is declared as `async` but has no explicit return type annotation.

**Comment by debonte** [comment]
@DanielRosenwasser, can you check your "minimal example" above? It is missing the `$` and seems like it might be a copy of the "actual behavior" code.

**Comment by DanielRosenwasser** [comment]
My apologies - I started out with the bottom example, figured it should be more minimal, but got sloppy. Fixed now.

Also, here's the same example [on the Pyright playground](https://pyright-play.net/?strict=true&enableExperimentalFeatures=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCCA7gIZIwkBGANgKYBQ9AxtSQM5tQBC7tAXPShCoAE1rAocEiJEkAFG1rVgASigBaAHyFS5KnQDaqGAF0Bwi1AB0NwcOasOUACK0QSAG60RcnopXmwuxwKEyi4pIkQA).

**Comment by heejaechang** [comment]
A retained repro workspace for this issue is available here:

https://github.com/heejaechang/pylance-repro/tree/main/pylance-issues/5542

It keeps the primary minimal Awaitable-based override-completion contract that still reproduces on current bits:

1. Create a local virtual environment in that folder.
2. Open `scenarios/issue_5542.py` in VS Code.
3. In `Derived`, place the cursor at the end of `async def ya`, trigger completion, and commit `yadda`.

Current behavior still generates an async override with `-> Awaitable[int]` instead of the expected unwrapped `-> int:` return annotation.

I used that same contract for the current-bits sweep rerun and kept the related `AsyncContextManager.__aenter__` drift as a note in the repro README rather than making it the primary scenario.

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2026.2.104, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20262104-3-June-2026-PreRelease)
