### ISSUE TITLE
Pylance crashes when using the interactive window

### ISSUE THREAD

**Issue by MarceloAritaAdvisia** [microsoft/pylance-release#6357]
## Environment data

-   Pylance version: v2024.8.2
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.14

## Code Snippet

```python
import torch
import numpy as np

```

## Repro Steps

1. Open a Python file in Visual Studio Code.
2. Start using the Pylance extension.
3. Observe that Pylance crashes multiple times within a few minutes.

## Expected behavior

Pylance should run without crashing and provide proper linting, autocompletion, and code analysis for Python files.

## Actual behavior

Pylance crashes repeatedly within a few minutes of usage, and it does not restart automatically.

## Logs

```
untitled:/Interactive-1.interactive.py
    at _0x4c4f8d (c:\Users\your-username\.vscode\extensions\ms-python.vscode-pylance-2024.8.2\dist\server.bundle.js:1:1072956)
    at _0xc0b312 (c:\Users\your-username\.vscode\extensions\ms-python.vscode-pylance-2024.8.2\dist\server.bundle.js:1:1077607)
    at _0x508620 (c:\Users\your-username\.vscode\extensions\ms-python.vscode-pylance-2024.8.2\dist\server.bundle.js:1:1078049)
    at c:\Users\your-username\.vscode\extensions\ms-python.vscode-pylance-2024.8.2\dist\server.bundle.js:1:1004156

2024-09-06 08:41:14.121 [info] [Error - 8:41:14 AM] Pylance has crashed 5 times in the last 3 minutes. Pylance will not be restarted. Please check [this link](https://aka.ms/AApf7ox) for more details.
```

**Comment by rchiodo** [comment]
Thanks for the issue. Unfortunately, we cannot reproduce the problem. Can you include the `Python Language Server` output as described here:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

That should show what's crashing in Pylance.

**Comment by cddesja** [comment]
I am having a similar problem. See the attached log file. I couldn't paste it here as it was too long.
[pylance_log.md](https://github.com/user-attachments/files/16931594/pylance_log.md)

**Comment by rchiodo** [comment]
@cddesja your problem is this:

2024-09-09 09:46:57.541 [info] Error: Debug Failure. False expression: Duplicate path in cellFilePaths: untitled:/Interactive-4.interactive.py#W1sdW50aXRsZWQ%3D
untitled:/Interactive-4.interactive.py#W2sdW50aXRsZWQ%3D
untitled:/Interactive-4.interactive.py#W3sdW50aXRsZWQ%3D
untitled:/Interactive-4.interactive.py#W4sdW50aXRsZWQ%3D

Looks like a bug in our interactive window handling. Same as this issue here:
https://github.com/microsoft/pylance-release/issues/6366

**Comment by rchiodo** [comment]
I'm able to reproduce following these steps here:

1. Create a python file with # %% cells
1. Execute a cell
1. Reload vscode without closing the interactive window
1. Execute another cell

Error shows up.

**Comment by rchiodo** [comment]
I think this is a bug in the vscode-languageclient-npm module. We're getting a did change event that has impossible start index. 

During the onDidNotebookDocumentChange event, the start index for the [NotebookCellArrayChange](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#notebookCellArrayChange) looks like it's including the markdown cells. It doesn't normally.

**Comment by rchiodo** [comment]
Nope, it was a bug in our own code. Maybe VS code started adding markdown cells to the interactive notebook recently and they weren't there before. The problem is we're not accounting for markdown cells when adding the Interactive input to the bottom of our cell list.

**Comment by ernimd** [comment]
Still an issue with `Last updated 2024-09-10, 09:40:38` : (

**Comment by rben01** [comment]
I am also seeing this. I can confirm that the repro is opening/restoring a VSCode workspace with an existing ipython pane (created by running `# %%` cells) open.

Extensions: Pylance v2024.9.1, Python v2024.14.0. 

Pylance logs:

```
2024-09-10 10:29:49.332 [info] Error: Debug Failure. False expression: Duplicate path in cellFilePaths: untitled:/Interactive-1.interactive.py#W1sdW50aXRsZWQ%3D



untitled:/Interactive-1.interactive.py
    at _0x3b1d9a (/Users/rben01/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/server.bundle.js:1:1040515)
    at _0x3c03f1 (/Users/rben01/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/server.bundle.js:1:1044937)
    at _0x4e65cb (/Users/rben01/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/server.bundle.js:1:1045372)
    at /Users/rben01/.vscode/extensions/ms-python.vscode-pylance-2024.9.1/dist/server.bundle.js:1:1001232

2024-09-10 10:29:49.344 [info] [Error - 10:29:49 AM] Server process exited with code 1.
2024-09-10 10:29:49.346 [info] [Error - 10:29:49 AM] Pylance has crashed 5 times in the last 3 minutes. Pylance will not be restarted. Please check [this link](https://aka.ms/AApf7ox) for more details.
```

**Comment by rchiodo** [comment]
Yes, the fix for this hasn't shipped yet. It should ship sometime this week.

**Comment by alejandro979** [comment]
Here are the logs for my case:
[2024-09-10 134649.323 [info] [Error.log](https://github.com/user-attachments/files/16948155/2024-09-10.134649.323.info.Error.log)

**Comment by rchiodo** [comment]
@alejandro979 your issue doesn't look to be the same problem. Are you using an interactive window? If not, it's something different. I recommend opening a new issue and add a full log as described here:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by rchiodo** [comment]
No, it's just weird that it's not logging the same error. Maybe your trace level isn't high enough.

Likely the same problem though. 

Our interactive window logic is just wrong. VS code must have updated to include markdown cells in the interactive window or otherwise it should have never worked.

**Comment by d-walkama** [comment]
+1 for issue, following for fix.

**Comment by dempc6469** [comment]
> +1 for issue, following for fix.

what he said .....

**Comment by PrateekArya** [comment]
Temp. fix: Close all interactive windows and restart VSCode. Pylance works perfectly then!

But there should be a setting to auto close all interactive windows while exiting VSCode. Added a feature request in VSCode (https://github.com/microsoft/vscode/issues/228206)! 😊

**Comment by rchiodo** [comment]
> If you can't roll out a hotfix, at least should provide the version of the extension without the bug

There is no version of the Pylance extension without this bug. It's existed since we added interactive window support. Rolling back VS code to 1.89 might fix the issue, but then you'd also have to rollback other things as well.

**Comment by rchiodo** [comment]
I've confirmed you can also rollback VS code to 1.89 and the problem went away for me. The Python Extension, the Pylance Extension, and the Jupyter Extension have to be rolled back to much older versions as well.

**Comment by Carolinah23** [comment]
Hi, I am reporting that I am having the same bug since yesterday.
```
2024-09-12 15:27:58.023 [info] [Error - 3:27:58 PM] Server process exited with code 1.
2024-09-12 15:27:58.023 [info] Error: Debug Failure. False expression: Chained file path untitled:/Interactive-1.interactive.py#pylancePrefixCell doesn't match cellFilePaths undefined
    at _0x3b1d9a (c:\Users\carol\.vscode\extensions\ms-python.vscode-pylance-2024.9.1\dist\server.bundle.js:1:1040945)
    at _0x3c03f1 (c:\Users\carol\.vscode\extensions\ms-python.vscode-pylance-2024.9.1\dist\server.bundle.js:1:1044937)
    at _0x4e65cb (c:\Users\carol\.vscode\extensions\ms-python.vscode-pylance-2024.9.1\dist\server.bundle.js:1:1045372)
    at c:\Users\carol\.vscode\extensions\ms-python.vscode-pylance-2024.9.1\dist\server.bundle.js:1:1001232

2024-09-12 15:27:58.027 [info] [Error - 3:27:58 PM] Pylance has crashed 5 times in the last 3 minutes. Pylance will not be restarted. Please check [this link](https://aka.ms/AApf7ox) for more details.
```
After several crashes, I installed the 2023.10.30 version, which seems to work fine.

**Comment by StellaHuang95** [comment]
This issue has been fixed in prerelease version 2024.9.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20249100-12-September-2024-PreRelease)

**Comment by polidore** [comment]
i confirm i am no longer having the issue on 2024.9.100

**Comment by cshjin** [comment]
A temp fix from my side: `pkill -u $USER`, if there are no critical jobs running, and restart vscode.

**Comment by scaomath** [comment]
I am still experiencing issues regarding the interactive window with 2024.9.2.
Rolling back to 2024.8.2 solves the issue.

**Comment by JasonBenn** [comment]
The company behind Cursor has their own Python language server now. 

Look up "Python" by Anysphere, uninstall Pylance, and that'll fix it.

**Comment by JacobSignal** [comment]
@JasonBenn I am unable to find Python by Anysphere - is this fix still valid?
