### ISSUE TITLE
Local imports not resolving correctly

### ISSUE THREAD

**Issue by aaronsmith1234** [microsoft/pylance-release#68]
## Environment data

-   Language Server version: 2020.6.1
-   OS and version: Windows 10 Version	10.0.18363 Build 18363
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.2 32bit

## Expected behaviour
When trying to import another python file from the same directory as the current file (e.g. main.py and emailRelay.py are in the same directory, and I am importing emailRelay.py into main.py), the import should not be linted unless file I am importing does not exist.

## Actual behaviour

When trying to import another python file from the same directory as the current file (e.g. main.py and emailRelay.py are in the same directory, and I am importing emailRelay.py into main.py), Pylance lints it as an unresolved import

**Comment by erictraut** [comment]
This is intended behavior. I presume you are using absolute imports. Python 2 allowed absolute imports to be resolved from the same directory as the importing file, but Python 3 always uses import search paths. By default, Pylance assumes that the root directory of your workspace is included in the search path. It also adds `src` if it's present, since it's common to place all sources within a local directory of that name. I'm guessing that your "main.py" and "emailRelay.py" are not in either of these default directories. If you would like to add additional directories to your import search path, you can do this by specifying these local directories in the `python.analysis.extraPaths` setting. All directories specified in this setting are assumed to be relative to the workspace root.

Alternatively, you can use relative paths (e.g. `from .emailRelay import X`).

**Comment by judej** [comment]
@aaronsmith1234, were you able to resolve the problem by using `python.analysis.extraPaths`? Please let us know if this is still an issue.

**Comment by aaronsmith1234** [comment]
Hey sorry, haven't had a chance to trial yet; will give it a shot in the next few days. The relative imports didn't work as expected; I'll provide some code samples when I give it a shot.

**Comment by RaghavaDhanya** [comment]
Is this behaviour intended to be different from old language server? This is making moving from old language server harder. I think the old language server behaviour is more useful
My use case: Developing a package `xyz` and I use absolute imports such as `from xyz import abc` inside the package, but pylance tries to resolve this in the installed packages rather than in current workspace where as the old language server did the opposite. Pylance forces me to either use relative imports(Which is not recommeded by PEP-8) or manually uninstall the package everytime from the development venv. The package is always in my dev venv for testing.

**Comment by erictraut** [comment]
Pylance will resolve imports in the workspace, but it will resolve from the top-level directory of your workspace. It will not (by default) resolve absolute imports from the same directory as your source file if that source file isn't at the top level of your workspace. That's intended because it matches the import resolution behaviors of the Python interpreter itself.

For more details about how Pylance/Pyright resolve imports, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/import-resolution.md).

**Comment by erictraut** [comment]
I'll also say that in my experience, relative imports are preferable to absolute imports for local files. PEP 8 says that both are acceptable.

**Comment by mrucker** [comment]
I feel like this discussion is missing an important nuance. That is, Python code can be executed by one of two means: (1) as part of an import and (2) as a script file. Depending on how code is executed import resolution can behave very differently.

When Python code is executed because of an import statement the resolution behavior of Python is not to resolve absolute imports from the same directory as your source file. In this case it is possible to use both absolute and relative imports and pylance seems to work great with import resolution (or has so far for me).

When Python code is executed as a script file, however, then the Python interpreter adds the scripts location to the search path
(see the first bullet [here](https://docs.python.org/3/tutorial/modules.html#the-module-search-path)). The search path addition ends up allowing resolution of absolute imports from the script file's directory at execution time.

The behavior of script files noted above only seems to be a problem for pylance/pyright when a project contains scripts files that aren't in the root of the project. When this is the case I have noticed three problems with import resolution checks (I want to say clearly though that none of this has changed how my code runs, just the error messages I see):

1. When the imports are absolute from the script's directory it will say things are wrong even though they are fine.
2. When the imports are relative from the scripts directory it will say things are good even though they are not fine.
3. When the imports are absolute from the workspace's root it will say things are good even though they are not fine.

To solve (1) and (2) pylance/pyright would have to magically know how a user intends to run a code file. I'm not sure there is any way for pylance to know that... To solve number (3) I think pylance should maybe not make the assumption that the root is in the search path. While I understand it is intended as a convenience for users, I think it is confusing. Maybe new projects should pop up a message asking users if they want workspace roots added to PYTHONPATH rather than just assuming?

It is also worth noting that issue (3) also applies to code that has been written assuming it will be executed through import. For example, if somebody is making their own package that they mean to distribute on PyPI. In this case the developer is likely savvy enough to not use absolute imports from root... or it will just works so long as the root package folder is in the workspace root or src which is pretty clearly the intention and I assume will almost always be the case. Still... I guess something to consider.

**Comment by jakebailey** [comment]
> To solve (1) and (2) pylance/pyright would have to magically know how a user intends to run a code file. I'm not sure there is any way for pylance to know that...

This is a time old problem for Python LSs (microsoft/python-language-server#1602). I think jedi is able to handle these cases differently by using a more loose import mechanism, where it goes up above the potential script's directory to find imports that might resolve, We've not done this because we'd rather show that an error could occur than to potentially mislead (even though looser is certainly friendlier).

(3) is an interesting case, though, as it represents a false negative. I'm not sure how we'd detect this case either, but I can say that the solution where we don't add the root as an import path would be a pretty significant change. Most people are going to fit into the category of projects that we currently support out of the box.

It'd be interesting to see if there were any tell-tale signs that a given file is a script, and if we could use that as a heuristic for determining imports. Or, add some configuration in `mspythonconfig.json` that says which files are scripts that need to have the root directory replaced with the script directory.

One thing you may also consider if you have a specific scripts directory is to add that directory as another workspace, so that we resolve imports for that "project" distinctly.

**Comment by erictraut** [comment]
Pyright (which forms the core of Pylance) solves this by allowing you to specify multiple "execution environments". Each script or program entry point represents its own execution environment. My team owns a large, complex python code base, and we have several dozen execution environments defined, some with different Python version requirements.

For more details about how to configure execution environments in Pylance or Pyright, check out this [documentation](https://github.com/microsoft/pyright/blob/master/docs/configuration.md#execution-environment-options). If you scroll to the bottom of that page, you'll find an example config file.

**Comment by jakebailey** [comment]
The only edge case I can see with execution environments would be the interpreter selection. Based on that, is it true that if you don't pick an interpreter in the config, you get the "default" one, which isn't what the editor is sending per-workspace but the global default?

If so, we may want to tweak things to use, say, the interpreter for the workspace VS Code declares that happens to contain the execution environment, to be more aligned with what the UI is saying.

**Comment by mrucker** [comment]
@jakebailey, yeah I couldn't think of any obvious better solutions myself while mulling it over today. I think the real problem with (1) and (2) is that they are likely going to cause the most trouble for more casual users since most expert users I imagine will likely use a pattern leveraging `pip install -e .` to separate re-usable code from scripts. Unfortunately, those are the users who I think are also going to be least likely to be able to find a solution on their own. Out of all the languages I've worked in up to this point in my career I've found learning Python imports to be one of the most frustrating language features ever. I haven't quite been able to put my finger on why that is though...

Anyway, I should end this by saying on the whole though I'm incredibly happy with Pylance so far. I think you've made a great tool for the community that has the potential to really take off. I've been using it for about a week now and have been super impressed.

**Comment by erictraut** [comment]
>Out of all the languages I've worked in up to this point in my career I've found learning Python imports to be one of the most frustrating language features ever.
I wholeheartedly agree with you there!

I agree that there's a tradeoff here. Do we make things easy for casual users at the expense of leaving holes in error reporting? In some cases, we've decided to switch behaviors based on the "python.analysis.typeCheckingMode" setting, under the assumption that casual users will leave it "off", whereas more advanced users who are interested in typing will switch it to "basic" or "strict". However, in this particular case, I wouldn't feel comfortable changing the import logic based on the typeCheckingMode setting.

**Comment by jakebailey** [comment]
> However, in this particular case, I wouldn't feel comfortable changing the import logic based on the typeCheckingMode setting.

Agree, I would rather introduce some other import resolution knobs, if possible, or do our best to document and improve execution environments.

**Comment by aaronsmith1234** [comment]
I'm still pretty new to Python, so a lot of this is new to me. I added some code to the repo below to show my main concern; if you look in "subfolder" and look at the "main2.py" file, you'll see that Pylance highlights the import as unresolved, but then the code runs successfully. I think that was my big concern; Pylance doesn't seem to be aligning with what Python is actually executing since Python can find the code and run it just fine. Again, I'm new to Python, so maybe there's a nuance I'm missing here.

Also take a look at "main3.py" in the subfolder as well. Here, I am using a relative import, as suggested. Pylance now can correctly resolve the import. However, when I try to actually run the code, it errors out with an invalid syntax error. If I get rid of the relative import, then Pylance again can't resolve the import, but the code runs successfully (since after removing the import main3=main2).

I think that the mismatch between the behavior of Pylance and the behavior of my Python install (which in this case was 3.8.3 32 bit, slightly different than what I opened the issue with, running on home machine!) is what should be aligned. Let me know if I'm missing something here!

https://github.com/aaronsmith1234/pythonSamples

**Comment by erictraut** [comment]
The Python import system is very confusing, even for experienced Python users.

The syntax you're using for relative imports is illegal. Pyright should have flagged it as such. I've fixed that hole in the parser. You can't use the form "import .import2". You need to use the form "from . import import2".

When you execute a script in Python, the interpreter automatically adds the directory of that script to the import search paths. When you execute "main3.py", you're implicitly adding that directory to the search path. Pyright has no way of knowing this is the main entry point to a script though. You haven't indicated that it's an independent "executable". That's why Pyright's configuration mechanism allows you to identify the various "execution environments" within your code base.

Try this experiment. 
* Starting with your sample code, fix the relative import as I mentioned above:
```
from . import import2
```

* At the end of main.py, add the following lines:
```
import subfolder.main3
import subfolder.main2
```
* Run `python main.py`

What you'll find now is that the relative import works fine, but the `import import2` generates a runtime exception, as predicted by Pyright.

**Comment by oh-mycode** [comment]
What do you offer to do in my case - I have a few packages which include contains python modules with the same name.
It looks like this:
```
p1
    module1.py
    main.py - inside here there is `import module1`
p2
    module1.py
    main.py - inside here there is `import module1`
```

if I add python.analysis.extraPaths path to p1 and p2 and in p2/main.py try to go to definition of module1
VS Code opens p1/module.py

**Comment by erictraut** [comment]
@oh-mycode, for a more complex situation like yours, you can define different "execution environments" in your pyrightconfig.json file, each with independent root directories and extra paths. For details, check out [this documentation](https://github.com/microsoft/pyright/blob/master/docs/configuration.md#execution-environment-options).

**Comment by mrucker** [comment]
Just wanted to add one more comment to this thread. I used `python.analysis.extrapaths` for the first time today and it worked great. All go to references started working and import resolution warnings went away. I didn't even have to restart vs code to get it to work.

**Comment by JosephTLyons** [comment]
I ran into this issue today and still don't quite understand why it is happening.

src
    main.py
    enums.py


in main.cpp

```python
from enums import BrushSize, Tool, Window # Import "enums" could not be resolvedPylance (reportMissingImports)
```

The Python interpret says that this is valid, but PyLance does not.  I'm using PyCharm and VS Code these days.  PyCharm's automatics import command is what wrote that line of code for the import.  I'm just not sure why PyLance keeps thinking its an error.  Is it that I have to a set a path setting for these, in VS Code, for each project?

What's really weird is I have other projects that use this same type of import (where the file is in the same directory as main.py) and PyLance isn't throwing an error on those like it is in this project, despite it seeming to be exactly the same.

**Comment by JosephTLyons** [comment]
> Out of all the languages I've worked in up to this point in my career I've found learning Python imports to be one of the most frustrating language features ever. I haven't quite been able to put my finger on why that is though

If you haven't used Rust, give it a try and see if its import system tops Python's in how frustrating it is...

**Comment by mrucker** [comment]
@JosephTLyons Given your code above I'm guessing your Pylance problem (i.e., why it complains sometimes and not others) has to do with your workspace root directory. The import itself is completely fine so long as you are running main.py using the `python` command on the command line.

**Comment by JosephTLyons** [comment]
> @JosephTLyons Given your code above I'm guessing your Pylance problem (i.e., why it complains sometimes and not others) has to do with your workspace root directory. The import itself is completely fine so long as you are running main.py using the `python` command on the command line.

Ok.  It just sank in.  I realize what is being said now.  Yeah, I'm remoting into a RaspberryPi, so my root is not the project's root, but the entire linux system, so PyLance doesn't understand the import from that location and tosses and error.  This makes sense.  If I remote into the project directory itself, then I have no errors.  Thanks, that helped clear it up.

**Comment by jakebailey** [comment]
I'm assuming you remoted in via the SSH remote extension, right? I've seen it just plop the editor straight into `/`, which is unfortunate for projects that need you to be in a different folder (plus, I'm really guessing that's going to make VSC unhappy as it attempts to set up file watchers for the entire filesystem).

I'm actually surprised that it works; last I knew, the SSH remote support for VSC created a virtual file system known only to the editor, but didn't actually provide "real" paths to LSs.

**Comment by ewerybody** [comment]
Oh well. This seems to be a returning issue, right? I mean I see the point:
Not all python files are supposed to run as scripts and highlightig this issue promotes more explicit code 👍 and Pylance team deserves applause for coming forward like this!

On the other hand: At least for me this has never been an issue with PyDev or Jedi and is highlighting something that just works **IF** a file is run as script! ...

So I wonder if it would be feasable to handle imports in an `if __name__ == '__main__':`-block accordingly and highlight only these outside such a block as unresolvable 🤔 Isn't that a pretty good "script-indicator"?

**Comment by jakebailey** [comment]
@ewerybody See #253 for script specific things. We don't really want to copy methods that lead to false negatives in import resolution; jedi's import resolution is "friendly" but isn't strict at all as a result

**Comment by ewerybody** [comment]
Yeah that's what I was referring to with:
> ... highlightig this issue promotes more explicit code 👍 and Pylance team deserves applause for coming forward like this!

🙂 For the 3rd paragraph: Shall I post this over there again?

**Comment by jakebailey** [comment]
No, that's okay. I'm already aware of heuristics about trying to use these main blocks to deduce the context, but I'm not certain it's a good idea. I linked that issue if you wanted to follow support for script-related fixes.

**Comment by tapetersen** [comment]
While looking at `if __name__ == "__main__":` blocks can often tell if it's to be executable it's used for both execution as script and as a module using `python -m package.path` and absolute imports are resolved from the script dir in the former case but not the latter. 

A decent heuristic that hasn't been mentioned though could be  checking for a shebang line as that is only really needed and used if executed as a script.

**Comment by dutzi** [comment]
I created a file named `pyrightconfig.json`, placed it in my project's root directory, and populated it with:

```
{
  "executionEnvironments": [
    {
      "root": "packages/core",
      "extraPaths": ["./"]
    },
    {
      "root": "packages/parsers",
      "extraPaths": ["./"]
    }
  ]
}
```

Worked great!

**Comment by saryeHaddadi** [comment]
Hello, I ran into the same issue (multiple python files, each in its own folder, not the projet root folder, and each file performing import of scripts inside its own folder).
I feel that making more visible how to handle that situation by configuring a pyrightconfig.json would be nice. A sort of official howto for this.

This issue has been my frustation n°1, I am glad to have found a solution. Thank you.

**Comment by bharathwajan** [comment]
i am using anaconda(python 3.8.5)  in vscode
i am importing the y.py  to the x.py  by saying   # note : both my x and y are on the same folder named blog
structure of the folder is
    blog
         x.py
         y.py
the statement i used for importing is

from .x import func_name

but i am having issues with the relative import saying that:
    Exception has occurred: ImportError
    attempted relative import with no known parent package
    File "C:\Users\lab\bharathwajan\blog\x.py", line 2, in <module>
    from .models import data

**Comment by jakebailey** [comment]
@bharathwajan I don't think this is related; I believe you're saying that we are reporting no error, but when you run the code, there is an error, which is different than this issue. I'd appreciate that in a new report.

If you stuck a `__init__.py` in the folder, I believe it would fix your problem, but that new issue could be handled by us knowing that imports will fail without that file (if it does fix it as I believe it does).

**Comment by bharathwajan** [comment]
i already had a file called __init__.py in my folder but eventhough its
showing me error

**Comment by heejaechang** [comment]
can you try setting this hidden option, in setting.json, "python.analysis.useImportHeuristic": true, and see whether it helps to resolve local imports? and whether it causes something to break? or whether it behaves differently than what you would expect?

**Comment by ricardoprins** [comment]
> can you try setting this hidden option, in setting.json, "python.analysis.useImportHeuristic": true, and see whether it helps to resolve local imports? and whether it causes something to break? or whether it behaves differently than what you would expect?

For me it helped perfectly. Thanks!

**Comment by ajkleinjsq** [comment]
@heejaechang Thanks for the tip! I am testing this currently but I wanted to highlight a use case that may be related and was not solved by turning on the hidden setting:

In our codebase, we have a module's `__init__.py` file that re-exports another module with the statement `from .othermodule import *`. Whether or not this is best practice aside, I would still expect Pylance to correctly route back to the source code when I click on a reference in the codebase and select "Go to definition". Instead, I get routed back to the `__init__.py` file.

In addition, and potentially a side effect of this behavior, is that when trying to add type definitions to a function, Pylance errors with "Module not allowed in this context". So for example

```python
def a_function() -> Tuple[ClassReference, bool] {
  pass
}
```

the `ClassReference` will show the error.

If I can provide any more info or clarification please let me know! Thanks for your consideration and work on this issue.

**Comment by jakebailey** [comment]
@ajkleinjsq I don't think that's related to this issue, and we'd appreciate a new issue with a repro.

**Comment by DanielNoord** [comment]
I believe the VS Code extension has now turned on Pylance by default, therefore throwing a number of errors in my imports. After some googling I found this issue and the solution of turning on the hidden setting. However, this is rather un-userfriendly, especially since Pylance was turned on without me doing so specifically.

While I appreciate the difficulty of the problem (see also #236) I think linking to this issue from the Troubleshooting page or providing more details for first-time users how to solve this might be welcome.

Furthermore, is there any timeline for when this hidden setting will be standard? I expect this might be up to the maintainers of the Python extension, but was hoping somebody here might know more.

**Comment by jlouis** [comment]
I was hit by this as well in a project I have. The reason is that the project uses 3-4 different programming languages, and since the Python code is a TensorFlow machine learning model, it logically resides in a subdirectory called `model`. The assumption that my code lives in the project root or under a `src` folder seems wrong to me. I don't want to give any of the 4 languages the root of the project for reason of organization of my code.

In general, I'm a bit perplexed by the notion that this is by design. Python 3.8.6 accepts the code, so why is Pylance complaining? I agree Python's import system is a regular mess, but I'm going to guess you will get a *lot* of error reports in the same vein as this one. Technically being correct doesn't necessarily translate to people's acceptance.

Using a relative import by

```
from . import preprocessing
```

like it was suggested earlier, leads to the following:

```
Traceback (most recent call last):
  File "model.py", line 23, in <module>
    from . import preprocessing
ImportError: attempted relative import with no known parent package
```

which is true. There is no parent package. Because `model.py` is what I execute on the command line when I want to train the ML model: `python model.py ...<flags>`

I'm pretty sure I'm doing *something* wrong in my Python import structure. Getting to a point where I could slice my code into several files took some work in the trial-and-error department. And it doesn't look nice. But on the other hand, it kinda worked, and I'm afraid to touch it too much because it leads to odd errors like the one above. So I'm quite happy in my little local extremum, even though a better solution might exist.

fwiw, setting `"python.analysis.useImportHeuristic": true` in VSCode solves the problem.

**Comment by jakebailey** [comment]
There's not a timeline at the moment; this setting is only an experiment and it _technically_ makes our import resolver break spec in an attempt to resolve more items (at the cost of hiding true errors). We're currently working on examining how it's affecting things like completion coverage / acceptance to make sure that it's a change we're willing to make, or how to better package it up (maybe we can detect this and offer to add roots to extraPaths? Auto-configure paths that make imports work? etc)

This feedback is definitely appreciated; it's helpful to know that it's helping you out. As you can see, actual feedback has been pretty scarce...

@jlouis For your case, you may be more interested in `extraPaths`, but the setting working is still good info.

**Comment by DanielNoord** [comment]
I checked some of my other projects that were not directly affected by the error and turning the setting on also did not produce any (user) noticeable errors. Do let me know if you would like me to test other stuff or send you any logs, always happy to help!

Offering to add roots to extraPaths seems to be a good solution. At least it notifies the user that what they are doing is functional python code but not "standard" or considered good practice. I am always in favour of providing such tips within linters and IntelliSense (although I can understand arguments against this).
However, one issue I would have is that this would necessitate creating a VS Code settings file in the project folder. I try to avoid this as not all users of a project might use VS Code and therefore that file would be extra clutter in a (often) already full root folder with settings and configurations files. Therefore, in this case perhaps opt-in auto-configuring might be better. Personally I would be happy with turning this setting on for all my projects, which would allow me to opt-in in my global settings. But other users might think differently and thus also need a project-settings file.

Seeing as this issue is already quite old you and the rest of the team have probably already discussed these issues. From a user perspective I think making the problem ("bad" code) and why it is a problem be clear is the first step and something to consider for the near-future. Just adding documentation to the FAQ/Troubleshooting page could already help some confused users.

**Comment by Carbaz** [comment]
Why assume the workspace rootdir is the root of the code?

```
my_workspace
├── my_project_1/
│   ├── CHANGELOG.md
│   ├── docs
│   │   └── source
│   │       ├── conf.py
│   │       └── my_project_doc.rst
│   ├── Makefile
│   ├── my_project_1
│   │   ├── __init__.py
│   │   ├── __main__.py
│   │   ├── code.py
│   │   └── more_code.py
│   ├── Pipfile
│   ├── Pipfile.lock
│   ├── README.md
│   ├── tests
│   │   └── unit    
│   │       └── pytest    
│   │           └── test_this.py
│   ├── TODO.md
│   └── VERSION 
│
└── my_project_2/
    ├── CHANGELOG.md
    ├── docs
    │   └── source
    │       ├── conf.py
    │       └── my_project_doc.rst
    ├── Makefile
    ├── my_project_2
    │   ├── __init__.py
    │   ├── __main__.py
    │   ├── code.py
    │   └── more_code.py
    ├── Pipfile
    ├── Pipfile.lock
    ├── README.md
    ├── tests
    │   └── unit    
    │       └── pytest    
    │           └── test_that.py
    ├── TODO.md
    └── VERSION
```
If i open workspace at my_project_1 it works well, but, if i open at my_workespace Pylance is raising wrong errors on a well structured project just because it's assumed that vscode must open code root folders as workspace root.

Obviously i'm not going to write all my imports with a dot trail at the star just to overcome this (or for any other reason, that's completely weird)
`from ....my_project_n.code import my_class` 
Which will not work even on any cli test scripts under tests folder.
`ImportError: attempted relative import with no known parent package`

And that structure is a simplification, I have projects with 6 or 7 levels deepth easily. ¬_¬

The "intended behavior" is assuming a really restrictive usage of the whole VScode environment.

**Comment by MikeKarnsTC** [comment]
I completely agree with Carbaz, I just had this thrown onto me because of the python extension update, and all of my local imports are now unresolved. I would not like to just turn off import checking, because sometimes I will actually have a typo or something, but it seems ridiculous that it cant resolve imports for a well structured project....

For now, I think I will downgrade my python extension until this gets figured out, I cannot understand why this would be included in the python extension for VS code when it can't handle something so rudimentary. It worked before, so lets break it, right?

**Comment by jakebailey** [comment]
There's no reason to downgrade the Python extension; if Pylance doesn't work right for you, you can uninstall it or change your `python.langaugeServer` setting to something else.

Have you both tried out the `"python.analysis.useImportHeuristic": true` option?

**Comment by MikeKarnsTC** [comment]
It seems that turns off resolving the imports, no? How will I know if I am actually missing an import? All I did was uninstall pylance extension and it went back to using jedi. I liked the look of many things from pylance, but yeah I'm not going to rewrite all of my applications to use absolute imports, not going to turn off import checking, and also not going to put additional directories to check in every project because I shouldn't need to.

So maybe I'll check back in the future, but for now, disable/uninstalling pylance was what I went with.

**Comment by jakebailey** [comment]
That is not what the setting does; the setting changes the import resolution algorithm to (if an import fails in user code) try absolute import starting at the file which is doing the import, going upward until the workspace root is hit. This means that if you have a `scripts` dir and do an import assuming that that dir will be in `sys.path`, it will find the imports.

**Comment by MikeKarnsTC** [comment]
Oh, ok, thanks for that explanation. That isn't going to work either, I don't think, because when using virtual environments and I don't think that the dir of my imports will be in sys.path. Gave it a try, but no luck.

Thanks for the help anyway, hope this is something that can eventually get worked out, although I realize its not particularly a bug. I had never used pylance until it was included in the python extension by default, but I did like the look of a lot of the features at a glance, it looked much better for navigating code than what I was used to.

**Comment by jakebailey** [comment]
Have you tried `extraPaths` to indicate that certain folders are import roots?

**Comment by swails** [comment]
What worked for me was setting `python.analysis.extraPaths`:

```json
{
    "python.analysis.extraPaths": [
        "${workspaceFolder}/path/to/lib1",
        "${workspaceFolder}/path/to/lib2"
    ]
}
```

I set this on the workspace settings and now all of my imports are resolving appropriately.  The main place this might fail is if lib1 and lib2 imports conflict (but in the majority of cases this would indicate a problem in how you handle imports and module/package names that needs fixing).

**Comment by MikeKarnsTC** [comment]
I'm likely just being lazy, but I maintain like 50 or so projects and it would be very inconvenient to have to explicitly define directories where for each project. Especially for some that have lots of subdirectories. If I did take that route and had a structure with subdirectories, would I have to explicitly define each subdirectory? or just the root?

for example, I have something like..
- project_dir
    - /src
        - __main__.py
        - /app
            - apps.py

would I need to add /src and /src/app? or just /src?

if it would be both.. from __main__.py, would I have to 
`import apps`
or
`import app.apps`
because it would seem if I'm explicitly telling it to look at subdirectories, then it would treat them all as if they were in the root?

I guess it just seems like a huge pain to explicitly define all subdirectories of a project, but maybe I only feel that way because I haven't had to do it up until now..

**Comment by swails** [comment]
@MikeKarnsTC - the extra paths need to contain just the packages in your project.  So if you have an `app/__init__.py` file, then you just need to add `${workspaceFolder}/src` to your extra paths.

If you don't use packages and just arrange "loose" python modules in a directory structure, then you need to explicitly add each of those directories into the extra paths (but you would also have to add them each to the setup.py file to get them installed correctly, anyway).

My suspicion is that the combination of extraPaths and importHeuristics covers the majority of use-cases comfortably.

**Comment by MikeKarnsTC** [comment]
Yeah that makes sense. Sounds like a reasonable solution, thanks for your help, both of you.

**Comment by MikeKarnsTC** [comment]
That does sound useful for quickly setting up a new project. 

I also didn't realize I could actually use variables with an .env file, so that since my projects are typically similarly structured, I could actually just use `./src/__init__.py` for all of my projects, stick to that structure, and wouldn't have issues, as swails suggested.

although it does seem this approach would have issues if there was a different project structure..

**Comment by Carbaz** [comment]
> There's no reason to downgrade the Python extension; if Pylance doesn't work right for you, you can uninstall it or change your `python.langaugeServer` setting to something else.
> 
> Have you both tried out the `"python.analysis.useImportHeuristic": true` option?

Downgrade? What? What kind of answer is that?
Just followed by a "You don't like it don't use it", Well, yes, that's the "BEST™" way to handle any error pointing comment ...
I can leave but that will not solve the problem, I don't even asked for any change, just presented the issue.

That "intended behaviour" is not working properly for well structured code, basically because it took for given an assumption: "workdir root is code root", which is false on many reasonable scenarios.

Pylance, despite the many real benefits and loveable features, is, in this specific case a downgrade as it's casting out false errors.

Moving from "Intended behaviour" to "Default behaviour + Alternate one/s" is not a downgrade, it's an improvement, especially when so many people is reasonably complaining because that specific behaviour.

About the "python.analysis.useImportHeuristic": true, good point and based on the behaviour you described it should solve the issue on vertical imports, not between same level folders on sub_projects but those might be covered by:

> We're also considering adding something to the right click menu of the file explorer, such that you could right click a folder and add it to extraPaths. Is that something that sounds useful?
> 
> Note also that you don't need `${workspaceFolder}`; just `./app` is fine, extraPaths will root from the workspace.

BUT: On a much more simpler and obvious  example of "brothers" imports:
Structure built here: [mw.zip](https://github.com/microsoft/pylance-release/files/6474696/mw.zip)
```
my_workspace
├── mp
│   ├── foo
│   │   ├── bar
│   │   │   ├── code_1.py
│   │   │   └── code_2.py
│   │   ├── code_3.py
│   │   └── code_4.py
│   ├── code_5.py
│   └── code_6.py
└── src
    ├── foo
    │   ├── bar
    │   │   ├── code_7.py
    │   │   └── code_8.py
    │   ├── code_9.py
    │   └── code_10.py
    ├── code_11.py
    └── code_12.py
```
All those imports works on runtime, but Pylance says:

WHITHOUT "useImportHeuristic"
- code_2: from code_1 import foo --> ERROR
- code_4: from code_3 import foo --> ERROR
- code_6: from code_5 import foo --> ERROR
- code_8: from code_7 import foo --> ERROR
- code_10: from code_9 import foo --> ERROR
- code_12: from code_11 import foo --> WORKS

WITH "useImportHeuristic"
- code_2: from code_1 import foo --> WORKS
- code_4: from code_3 import foo --> WORKS
- code_6: from code_5 import foo --> WORKS
- **code_8: from code_7 import foo --> ERROR**
- **code_10: from code_9 import foo --> ERROR**
- code_12: from code_11 import foo --> WORKS

Unreasonably the examples code_8 and code_10 fails in exactly the same scenario (despite the first level 
folder names) of importing a same folder module that code_4 and code_6 success.

Am I missing something or might it be some underlying issue with the alternate import resolution algorithm searching for ascending matches?

**Comment by jakebailey** [comment]
> Downgrade? What? What kind of answer is that?

This was a specific response to a specific comment; I'm just trying to clarify the way that the Python extension chooses which language server uses. Obviously, we want people to use Pylance, but we went through significant amounts of effort to ensure that the other options are still functional and easy to switch to.

> Unreasonably the examples code_8 and code_10 fails in exactly the same scenario (despite the first level
folder names) of importing a same folder module that code_4 and code_6 success.

Those two not working sounds like a bug in the import algorithm, so this reproduction is definitely useful, thanks.

**Comment by Carbaz** [comment]
> 
> > Unreasonably the examples code_8 and code_10 fails in exactly the same scenario (despite the first level
> > folder names) of importing a same folder module that code_4 and code_6 success.
> 
> Those two not working sounds like a bug in the import algorithm, so this reproduction is definitely useful, thanks.

Glad to help :smiley:

**Comment by jakebailey** [comment]
Ah, yes, that's an expected limitation at the moment; this heuristic doesn't play well with "autoSearchPaths" (which added src to extraPaths), as we skip this heuristic in extraPaths as we don't know which paths are actually "user" code (as opposed to pointing to library code).

**Comment by kandersondaxsonics** [comment]
If it works when you run Python itself (from the interpreter specified in `python.pythonPath`), and doesn't work with Pylance _by default_ then it doesn't work.  **Period**  Any other standard doesn't make sense.  You shouldn't need to add sub-directories specifically, or `useImportHeuristic` or anything else.

I wondered why my linting stopped working a few days ago.  This is why.

**Comment by swails** [comment]
> If it works when you run Python itself (from the interpreter specified in `python.pythonPath`), and doesn't work with Pylance _by default_ then it doesn't work. **Period**

The problem with this sentiment is that Python itself employs a well-known heuristic when constructing `sys.path` -- namely it adds the current working directory and `__file__` directory to the standard search path.  Since the editor lacks that context, the best you can do is define heuristics that try and predict where users might envision themselves working from.

**Comment by jlouis** [comment]
Some of the underlying problem stems from Python's handling of paths, and some of it stems from VSCode making heuristic assumptions about workspaces. It isn't really the responsibility of Pylance to handle this, I think. Other languages are easier to handle because they have a *witness* file in the directory structure:

* `Go`: There is a `go.mod` file in a parent directory.
* `OCaml`: Suppose you use `Dune` as your build tool. Then there is a `dune-project` file in a parent directory.
* `C`: Dependent on make-system, you can often just run `make` in any directory and the build happens.

Thus, there is no need for `extraPaths` or heuristics. The build tool itself thought about this.

In Python, however, there is an implicit idea that the current working directory is the basis for the "build" or import. Probably not a bad decision in a dynamic environment where there is no concept of "building the software". However, you run into trouble as soon as you want a statics phase; Pylance being one example.

The reason people don't like editor-specific knobs is because it locks you into that editor. If a better editor comes by, or you have a user who wants to use a different editor, you are now stuck. People who have been burned before by this develops a mistrust to editor-specific configuration. It leads to an insight: build systems must by and large be independent on the editor choice.

**Comment by kandersondaxsonics** [comment]
Blah @swails your point is fair.  Reverse-engineering the entire Python path resolution in a static tool (as per what @jlouis said) is a bit much, so I'll back up a bit.

My problem (and probably that of *many* of the comments here, as well as users that never find this issue) is that are already doing something like this (thanks to @Carbaz for the directories) :

my_workspace
```
|── project1
└── really_not_src
    └── subdir_for_whatever_reason
        ├── spam.py
        └── eggs.py
```
And in `spam.py`
```python
from eggs import poached

# other stuff
```
It's the *current directory* imports that are missing is what gets a lot of people I think.  So not just "root" and not just "/src" but if you have two python files in the same directory, no matter where in the directory tree, they can't "import" each other and Pylance  see the definitions.

That's weird.  Fix that (*by default*) and I think that solves most people's issues, that for the current path of the current file, the current directory is a valid search path for a module, [just like the first line in the doc on modules says](https://docs.python.org/3/tutorial/modules.html#the-module-search-path).

**Comment by swails** [comment]
> It's the _current directory_ imports that are missing is what gets a lot of people I think.

This particular case is pretty well-defined Python behavior.  I'm not sure how pylance is designed.  If it has a static set of paths where it looks for modules in every file, then adding the containing-folder rule wouldn't be possible (it'd have to add every folder that contains any Python script in your workspace).  This implementation strikes me as easier to write *and* optimize.

It still gets hard, though, since this rule should be disregarded for modules inside packages, though (implicit relative imports stopped working in Python 3).

I would naively expect any Python command that can run without a CWD context to also work in pylance, and it seems that it currently falls short for colocated, standalone modules.  I can appreciate that implementing this behavior might be a challenge, especially if it runs against the grain of current design decisions.

**Comment by jakebailey** [comment]
> It's the current directory imports that are missing is what gets a lot of people I think. So not just "root" and not just "/src" but if you have two python files in the same directory, no matter where in the directory tree, they can't "import" each other and Pylance see the definitions.

> That's weird. Fix that (by default) and I think that solves most people's issues, that for the current path of the current file, the current directory is a valid search path for a module, just like the first line in the doc on modules says.

FWIW, this is _exactly_ what we are trying to solve with this WIP "heuristic" feature, but it's a tradeoff of false errors for missing errors that would be useful, plus knowing that it's actually working.

The heuristic says "if the import failed, check the file's directory to see if it could be resolved there, if not, go one dir up and check again, and so on".

**Comment by MikeKarnsTC** [comment]
> > It's the current directory imports that are missing is what gets a lot of people I think. So not just "root" and not just "/src" but if you have two python files in the same directory, no matter where in the directory tree, they can't "import" each other and Pylance see the definitions.
> > That's weird. Fix that (by default) and I think that solves most people's issues, that for the current path of the current file, the current directory is a valid search path for a module, just like the first line in the doc on modules says.
> 
> FWIW, this is _exactly_ what we are trying to solve with this WIP "heuristic" feature, but it's a tradeoff of false errors for missing errors that would be useful, plus knowing that it's actually working.
> 
> The heuristic says "if the import failed, check the file's directory to see if it could be resolved there, if not, go one dir up and check again, and so on".

Yeah but.. that doesn't work with virtual environments which are a pretty integral part of a good project structure. Jedi seems to implement a working system (as long as you select the interpreter from the virtual env), although I haven't taken any time to look into how, so I won't pretend I did. As soon as you want to use a virtual environment, you have to implement the additional dirs.

**Comment by jakebailey** [comment]
I don't understand what this has to do with virtual environments. Virtual environments are third party code that this behavior doesn't impact; those import roots are set by the interpreter and we pick them up via `sys.path`. We're definitely not going to be applying this import resolver change anywhere other than in the workspace.

**Comment by swails** [comment]
> FWIW, this is _exactly_ what we are trying to solve with this WIP "heuristic" feature, but it's a tradeoff of false errors for missing errors that would be useful, plus knowing that it's actually working.

There are two parts of this heuristic:

* If the import failed, check the file's directory to see if it's resolved there.
* If it's still not resolved, walk up the directory tree to the workspaceFolder trying each location on the way.

What *I* might do is build the first bullet into the default behavior, and make the heuristic *just* do the second bullet.

**Comment by jakebailey** [comment]
That's a good point, and we are collecting info about just how far this heuristic has to walk up to find a working import root to inform that choice. IIRC we have found that your suggestion is largely enough to do what people expect.

**Comment by swails** [comment]
In most projects I've worked with, "how far up" is almost always "up until the first directory that doesn't contain an `__init__.py` file.  The one exception is I've often seen `__init__.py` files missing in test directories that are put inside a package (probably because then they _don't_ become subpackages).  So while the rule "go up until you don't see an `__init__.py` and stop" will work for most cases, there is still a very common pattern where this won't work for tests.

**Comment by Carbaz** [comment]
> In most projects I've worked with, "how far up" is almost always "up until the first directory that doesn't contain an `__init__.py` file. The one exception is I've often seen `__init__.py` files missing in test directories that are put inside a package (probably because then they _don't_ become subpackages). So while the rule "go up until you don't see an `__init__.py` and stop" will work for most cases, there is still a very common pattern where this won't work for tests.

Namespace packages are defined by not having a __init__.py file.
You can not rely on their presence to decide if you has reached the top of the "import tree".

If you have interest on reading about them : `https://www.python.org/dev/peps/pep-0420/`

**Comment by squarewave24** [comment]
is this issue resolved? 

i am using `./src` for python code and after switching to pylance i all my imports are broken. 

i tried all 3 settings with no luck

```
"python.analysis.useImportHeuristic": true
"python.analysis.extraPaths": "src"
"python.analysis.autoSearchPaths": true
```

**Comment by erictraut** [comment]
The `extraPaths` setting requires an array of paths. Please try: `"python.analysis.extraPaths": ["src"]` and let us know if that works.

**Comment by squarewave24** [comment]
updated to these +  restarted VS 

```
    "python.analysis.useImportHeuristic": true,
    "python.analysis.autoSearchPaths": true,
    "python.analysis.extraPaths": ["src"],
```
imports still failing with: 

```
Unable to import 'my.module'pylint(import-error)
No quick fixes available
```

**Comment by jakebailey** [comment]
Pylance isn't pylint; pylint is a linter which these settings don't affect.

Consider setting `"python.linting.pylintEnabled": false`, or changing your pylint settings to not warn about imports.

Related: https://github.com/microsoft/vscode-python/issues/16150

**Comment by squarewave24** [comment]
ah good point thanks.  updated linter to flake8 and that seems to have fixed issue above.

so how can i confirm that Pylance is configured correctly for ./src ?

**Comment by jakebailey** [comment]
By default, imports that are rooted at `src` should work, so long as `src/__init__.py` does not exist. Otherwise, see https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#unresolved-import-warnings.

**Comment by AlexWennerDT** [comment]
> can you try setting this hidden option, in setting.json, "python.analysis.useImportHeuristic": true, and see whether it helps to resolve local imports? and whether it causes something to break? or whether it behaves differently than what you would expect?

This helped me as well!

**Comment by jakebailey** [comment]
> Unreasonably the examples code_8 and code_10 fails in exactly the same scenario (despite the first level
folder names) of importing a same folder module that code_4 and code_6 success.

@Carbaz

FYI, this limitation was fixed in a recent release, so things provided in extraPaths or src will still have the heuristic applied and all of the examples you've given should work consistently.

**Comment by Carbaz** [comment]
> > Unreasonably the examples code_8 and code_10 fails in exactly the same scenario (despite the first level
> > folder names) of importing a same folder module that code_4 and code_6 success.
> 
> @Carbaz
> 
> FYI, this limitation was fixed in a recent release, so things provided in extraPaths or src will still have the heuristic applied and all of the examples you've given should work consistently.

Great news Jake, thanks for sharing!

**Comment by killerkalamari** [comment]
Pylance also fails if Python has a built in module with the same name as a custom module (such as parser.py which shadows the parser module). It runs fine but pylance won't properly recognize the import. The only workaround I could find was to change the name, so something like parser_.py, and then update all references in the program to use the new module name. Just a heads up for anyone else that might run into this version of the pylance bug.

**Comment by jakebailey** [comment]
I'm going to close this; we actually made the above change in 2021.8.2; the heuristic is now enabled for everyone, and you can delete the unused setting.

**Comment by niccolomineo** [comment]
Hi, I am still getting warnings re the missing imports on the 1.61.2. I am using the Remote Containers extension - not sure whether this is relevant at all.

<img width="429" alt="Schermata 2021-11-03 alle 11 45 04" src="https://user-images.githubusercontent.com/5409469/140048606-ee329a4a-7916-4431-9817-f6032693a8b4.png">
.
